### PR TITLE
Implement UI with draggable boxes

### PR DESCRIPTION
**Pull request by arcusmaximus**
\+ Fix infotext not getting saved to params.txt

### CODE REVIEW

**Comment by rktvr** [comment]
this works really well! i hope it gets added soon.

**Comment by arcusmaximus** [comment]
Also fixed the `'NoneType' object is not iterable` error when an image dimension is not a multiple of 64. It turns out the mask size calculation in the original code's `get_mask()` function isn't entirely correct - I copied the code from the Regional Prompter extension instead (and added a line to the credits comment).

**Comment by arcusmaximus** [comment]
Some more updates. Now it's always safe to leave the main prompt box (background prompt) empty:
* If the user-defined regions don't cover the whole image, the extension will add a dummy region that fills (only) the uncovered areas with prompt `_`.
* If the user-defined regions do cover the whole image, this dummy region will not be added to ensure zero impact.

If there is a background prompt, it will apply to the whole image as before.

**Comment by arcusmaximus** [comment]
Rebased to make this easier to merge than copying bits of code at a time :)

**Comment by arcusmaximus** [comment]
Please let me know if you intend to merge this. (If you do, I can resolve the merge conflicts once more.)

**Comment by Haoming02** [comment]
Welp, the stupid reason why I wasn't merging this is because I'm too stupid to understand TypeScript...

*(And some functions are different from what I had in mind)*

**Comment by Haoming02** [comment]
I'll also add a link to your fork once I finish my branch though
Thanks for your hard works

**Comment by arcusmaximus** [comment]
Thanks for the quick reply. I'd rather not keep my fork separate - the Stable Diffusion UI landscape is already way too fragmented as it is. I mean:

We have A1111 with Regional Prompter...
except A1111 has bad memory management, so we got Forge...
except Forge doesn't support Regional Prompter well, so we got Forge Couple...
except Forge Couple's UI is hampered by Gradio, so we got A8R8...
I really don't want to add *another* step that goes "except A8R8 lacks A1111's many extensions so we got Forge Couple Arc Edition." If anything, I'd want to take a step *back* and go "and then Forge Couple got a proper UI making A8R8 unnecessary."

If you don't know Typescript, this is the perfect opportunity to learn it. It's really not that hard and makes your code much more maintainable.

And if you had something else in mind for certain functions, let's discuss and come to a middle ground.

**Comment by arcusmaximus** [comment]
> BTW A8R8 is more than just a Forge Couple interface :)

Sure - I was just referring to this [Reddit post](https://www.reddit.com/r/StableDiffusion/comments/1brjy85/experimenting_with_regional_prompting_with_a8r8/) where you wrote that

> [Forge Couple's] Gradio interface is painful to use when it comes to mask definition, esp when defining multiple masks that work together, that was one of the main reasons I created a completely new interface that gives more freedom and context to the user.

**Pull request closed without merging**
